name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build Merkurius/Merkurius.csproj --configuration Release
    - uses: actions/download-artifact@v2
      with:
        path: Merkurius/bin/Release/netstandard2.1/Merkurius.dll
    - name: Display structure of downloaded files
      run: ls -R
